### ISSUE TITLE
Clarify Polaris GPU support

### ISSUE THREAD

**Issue by dooglz** [ROCm/ROCm.github.io#10]
Docs at:

https://github.com/ROCm/ROCm.github.io/blob/e4331ed2ca5e65a7a7be57339721309f68bd376b/hardware.md#rocm-platform-supports-two-graphics-core-next-gcn-gpu-generations

only includes RX 4X0 cards, assuming 5XX polaris cards are supported too?

**Comment by gstoner** [comment]
What was document what was tested,  we do not always get the consumer production cards to test.    I would use the new 1.7.1 we rolling out for 5xx support.

**Comment by jlgreathouse** [comment]
The page has been majorly updated since this was opened. Closing as I hope things are more clear now.
