### ISSUE TITLE
Hi, thx for the porting guide for cnn related stuff. do you know any where, I could find rnn miopen-cudnn-porting guide, thx?

### ISSUE THREAD

**Issue by Joejiong** [ROCm/ROCm.github.io#39]
Hi, thx for the porting guide for cnn related stuff. do you know any where, I could find rnn miopen-cudnn-porting guide, thx?

**Comment by saadrahim** [comment]
This repository is no longer maintained. Please file a new ticket at [ROCm](https://github.com/RadeonOpenCompute/ROCm) if required.
